# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - desafio-java-springboot-compasso-mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql-local
      MYSQL_DATABASE: catalogo_produtos
volumes:
  desafio-java-springboot-compasso-mysql:
