spring:
  datasource:
    url: jdbc:mysql://${DATASOURCE_HOST:127.0.0.1}:${DATASOURCE_PORT:3306}/catalogo_produtos
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql-local
  jpa:
    hibernate:
      ddl-auto: update
