spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/catalogo_produtos
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql-local
  jpa:
    hibernate:
      ddl-auto: update

